{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mhy.social",
    "module": "wx",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "wx-1.3.3.aar",
          "url": "wx-1.3.3.aar",
          "size": 41582,
          "sha512": "e2bd4716f93ef2dd85090fffc6a4d1a050a5edaae4aee8f62eb4ac7f80960e998b8d39a200684ca92b660ef09ec23f06698858305a2070b85e9cb75555250fe6",
          "sha256": "20893cf03e1ff1b9490f67b3f00515f25a60d4cd9efb4f5cf2397ac0950af3e5",
          "sha1": "e8072d5a3a5f075eaf542a0908e129d8b34f6bfd",
          "md5": "313f96a2a6d297758da82285646f2c72"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "wx-1.3.3.aar",
          "url": "wx-1.3.3.aar",
          "size": 41582,
          "sha512": "e2bd4716f93ef2dd85090fffc6a4d1a050a5edaae4aee8f62eb4ac7f80960e998b8d39a200684ca92b660ef09ec23f06698858305a2070b85e9cb75555250fe6",
          "sha256": "20893cf03e1ff1b9490f67b3f00515f25a60d4cd9efb4f5cf2397ac0950af3e5",
          "sha1": "e8072d5a3a5f075eaf542a0908e129d8b34f6bfd",
          "md5": "313f96a2a6d297758da82285646f2c72"
        }
      ]
    }
  ]
}
