{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mhy.social",
    "module": "common",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.3.1.aar",
          "url": "common-1.3.1.aar",
          "size": 29898,
          "sha512": "652a2bc004162210d715d3f4406f20f71483de704c8cabf06dc67f19fc856eca2fd6c121b3f5266ecf5f880de0dcfcf1e40041402702585dbcf6ba6bd66d025d",
          "sha256": "78aac9e2818d957ebb63c10ffcc4559157917e1fb1e4ab1d5a92768c1ddeffb6",
          "sha1": "dcce2081e8d1f99373fb0295477f0b41bf8aef1e",
          "md5": "74eca4336f707618625ce4335129727d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.3.1.aar",
          "url": "common-1.3.1.aar",
          "size": 29898,
          "sha512": "652a2bc004162210d715d3f4406f20f71483de704c8cabf06dc67f19fc856eca2fd6c121b3f5266ecf5f880de0dcfcf1e40041402702585dbcf6ba6bd66d025d",
          "sha256": "78aac9e2818d957ebb63c10ffcc4559157917e1fb1e4ab1d5a92768c1ddeffb6",
          "sha1": "dcce2081e8d1f99373fb0295477f0b41bf8aef1e",
          "md5": "74eca4336f707618625ce4335129727d"
        }
      ]
    }
  ]
}
