{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gitee.mahongyin.social",
    "module": "qq",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qq-1.3.1.aar",
          "url": "qq-1.3.1.aar",
          "size": 354564,
          "sha512": "ec245851ab655ed8369c6c5495d11c2fd38fab9c84dc213f6c4f9eb79c06abf87374e4d82046fb376158ec28067d04d9e254bd3195dd6ecc373ae6dbcef2c1a6",
          "sha256": "664648ae1650936f51509780f9ae72f24981087eec3efc38c982ef433ef5404a",
          "sha1": "0bf0ebeecc51a65aae71071abe17b7980b0cd202",
          "md5": "33db7f3a49d7784ac790e4d71413b39d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qq-1.3.1.aar",
          "url": "qq-1.3.1.aar",
          "size": 354564,
          "sha512": "ec245851ab655ed8369c6c5495d11c2fd38fab9c84dc213f6c4f9eb79c06abf87374e4d82046fb376158ec28067d04d9e254bd3195dd6ecc373ae6dbcef2c1a6",
          "sha256": "664648ae1650936f51509780f9ae72f24981087eec3efc38c982ef433ef5404a",
          "sha1": "0bf0ebeecc51a65aae71071abe17b7980b0cd202",
          "md5": "33db7f3a49d7784ac790e4d71413b39d"
        }
      ]
    }
  ]
}
