{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gitee.mahongyin.social",
    "module": "common",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.3.1.aar",
          "url": "common-1.3.1.aar",
          "size": 29914,
          "sha512": "5ba8381ad6dae02f812d9bc827d802151b5f05d07e38699407e976aa15ca01b01ecc8fddaf1082dd94e6270e048674df60b59b5219ca2731ac697f54f7ccb8ca",
          "sha256": "8d5f1ea99e4dc1da41cd2df48c274b9fce7ab0783e0a38cd018f8a58c3e60a3a",
          "sha1": "666381e344ce4de1be17afbaf19991e24d855178",
          "md5": "d2e805922861a7e95e929fffeee10c24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.3.1.aar",
          "url": "common-1.3.1.aar",
          "size": 29914,
          "sha512": "5ba8381ad6dae02f812d9bc827d802151b5f05d07e38699407e976aa15ca01b01ecc8fddaf1082dd94e6270e048674df60b59b5219ca2731ac697f54f7ccb8ca",
          "sha256": "8d5f1ea99e4dc1da41cd2df48c274b9fce7ab0783e0a38cd018f8a58c3e60a3a",
          "sha1": "666381e344ce4de1be17afbaf19991e24d855178",
          "md5": "d2e805922861a7e95e929fffeee10c24"
        }
      ]
    }
  ]
}
