{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mhy.social",
    "module": "qq",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qq-1.3.1.aar",
          "url": "qq-1.3.1.aar",
          "size": 354685,
          "sha512": "b3d4f0f0872bfea8533ac76cdb5ba481d1be47d3d138f099ad55a17f318253dfacb3d5e53e57aa3241fd55b01f4d78c1db5fac7be1f8a4be80a388d402612509",
          "sha256": "52afd98f8c2ae0da6d75b701e28a67bced44110e57782fb83c9521b7d2f9a742",
          "sha1": "67351ae685823771de97c3bc8875b66b6d355eb9",
          "md5": "4b160634a4b1160b0f0f2ba35bd10473"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qq-1.3.1.aar",
          "url": "qq-1.3.1.aar",
          "size": 354685,
          "sha512": "b3d4f0f0872bfea8533ac76cdb5ba481d1be47d3d138f099ad55a17f318253dfacb3d5e53e57aa3241fd55b01f4d78c1db5fac7be1f8a4be80a388d402612509",
          "sha256": "52afd98f8c2ae0da6d75b701e28a67bced44110e57782fb83c9521b7d2f9a742",
          "sha1": "67351ae685823771de97c3bc8875b66b6d355eb9",
          "md5": "4b160634a4b1160b0f0f2ba35bd10473"
        }
      ]
    }
  ]
}
