{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mhy.social",
    "module": "wb",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.sinaweibosdk",
          "module": "core",
          "version": {
            "requires": "13.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "core",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "wb-1.3.1.aar",
          "url": "wb-1.3.1.aar",
          "size": 27498,
          "sha512": "e9cfc6b14684e867128e7f88f2560116f0b89441bda1398f2463ad47a7f1f2de07da0c2759c31091cbe17af73933ab1b160a2376fddb9059eb0e9a06782901ff",
          "sha256": "8aa9302fe131de589026cfef0b1217ade6ca8fd55482a7282cc1cebacad7f7a6",
          "sha1": "16c65dd336064fc732b41223829a0b40c56f859c",
          "md5": "b9191dcf1693d099624c7810c0f53948"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.sinaweibosdk",
          "module": "core",
          "version": {
            "requires": "13.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "core",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "wb-1.3.1.aar",
          "url": "wb-1.3.1.aar",
          "size": 27498,
          "sha512": "e9cfc6b14684e867128e7f88f2560116f0b89441bda1398f2463ad47a7f1f2de07da0c2759c31091cbe17af73933ab1b160a2376fddb9059eb0e9a06782901ff",
          "sha256": "8aa9302fe131de589026cfef0b1217ade6ca8fd55482a7282cc1cebacad7f7a6",
          "sha1": "16c65dd336064fc732b41223829a0b40c56f859c",
          "md5": "b9191dcf1693d099624c7810c0f53948"
        }
      ]
    }
  ]
}
