{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mhy.social",
    "module": "qq",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qq-1.3.4.aar",
          "url": "qq-1.3.4.aar",
          "size": 340244,
          "sha512": "febcdacb8074e93c91eaff89510d01dc790a4d9531cb40daee2625842e5e6e93d87ec21e4196d3d3b53c72a3e27e427185b722702012be01c7ab0b68da1a2278",
          "sha256": "b58b9a2de12fddb957f0d3ca5e87d0ec602afb6058527e77aeccfe7315a0a3af",
          "sha1": "556c59d972a278dcf86abbf86298d0c72e281213",
          "md5": "90212f3ebb088d7080ae513b8a01e335"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qq-1.3.4.aar",
          "url": "qq-1.3.4.aar",
          "size": 340244,
          "sha512": "febcdacb8074e93c91eaff89510d01dc790a4d9531cb40daee2625842e5e6e93d87ec21e4196d3d3b53c72a3e27e427185b722702012be01c7ab0b68da1a2278",
          "sha256": "b58b9a2de12fddb957f0d3ca5e87d0ec602afb6058527e77aeccfe7315a0a3af",
          "sha1": "556c59d972a278dcf86abbf86298d0c72e281213",
          "md5": "90212f3ebb088d7080ae513b8a01e335"
        }
      ]
    }
  ]
}
