{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mhy.social",
    "module": "ali",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.alipay.sdk",
          "module": "alipaysdk-android",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "alipaysdk-android",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ali-1.3.3.aar",
          "url": "ali-1.3.3.aar",
          "size": 28309,
          "sha512": "f087692eba16bd5f4d444639a9f45a98d4a21616c1fdd58ae18cd316787b5199e977bec2e522b686bac27f541ac1e3c9f3e6922818e348a5f69d007227ce4867",
          "sha256": "55191542e29a8198a179caa2316308c88526c2fefac686765b653ce418239f77",
          "sha1": "d92db7c576e7cdc5eb811da98d8e7282f293c73d",
          "md5": "bf264ad1072476f64835b8fed445a988"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.alipay.sdk",
          "module": "alipaysdk-android",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "alipaysdk-android",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ali-1.3.3.aar",
          "url": "ali-1.3.3.aar",
          "size": 28309,
          "sha512": "f087692eba16bd5f4d444639a9f45a98d4a21616c1fdd58ae18cd316787b5199e977bec2e522b686bac27f541ac1e3c9f3e6922818e348a5f69d007227ce4867",
          "sha256": "55191542e29a8198a179caa2316308c88526c2fefac686765b653ce418239f77",
          "sha1": "d92db7c576e7cdc5eb811da98d8e7282f293c73d",
          "md5": "bf264ad1072476f64835b8fed445a988"
        }
      ]
    }
  ]
}
