{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gitee.mahongyin.social",
    "module": "wx",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "wx-1.3.1.aar",
          "url": "wx-1.3.1.aar",
          "size": 39436,
          "sha512": "9bff6b143e1c16864064a1fd204b76b2cf2fc2b785071010c45b550914031bf96e1db52967f8ff2aabe928f81ed34c6817c049f4dcec8178e916206a284baf58",
          "sha256": "4a06cf6463102004d60e04bdbf10f466973b0c2e325daf8b8a8975a7ffa59f37",
          "sha1": "8987e52d6b708c1b0deb4f02be3c13252c42cbd3",
          "md5": "e76af652a718c29e48087ed601be38c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "wx-1.3.1.aar",
          "url": "wx-1.3.1.aar",
          "size": 39436,
          "sha512": "9bff6b143e1c16864064a1fd204b76b2cf2fc2b785071010c45b550914031bf96e1db52967f8ff2aabe928f81ed34c6817c049f4dcec8178e916206a284baf58",
          "sha256": "4a06cf6463102004d60e04bdbf10f466973b0c2e325daf8b8a8975a7ffa59f37",
          "sha1": "8987e52d6b708c1b0deb4f02be3c13252c42cbd3",
          "md5": "e76af652a718c29e48087ed601be38c6"
        }
      ]
    }
  ]
}
