{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mhy.social",
    "module": "common",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.3.3.aar",
          "url": "common-1.3.3.aar",
          "size": 30311,
          "sha512": "33310bf6273dc321abc55a13b1057a2df661579a9d759a296ddbbf2b99e7b32898111de6b4d98b473bb610b05665b0c6e336d4033f0baf680e7333ae39450a44",
          "sha256": "2bbed01d986ad4065b3c9e3cd78b5786399fa224ca52be19a19f0ef08721a106",
          "sha1": "4d9db7838f0dfed743e3c1ddab137c71a8741ea7",
          "md5": "7564723d9d90c88299cd9795552fb11b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.3.3.aar",
          "url": "common-1.3.3.aar",
          "size": 30311,
          "sha512": "33310bf6273dc321abc55a13b1057a2df661579a9d759a296ddbbf2b99e7b32898111de6b4d98b473bb610b05665b0c6e336d4033f0baf680e7333ae39450a44",
          "sha256": "2bbed01d986ad4065b3c9e3cd78b5786399fa224ca52be19a19f0ef08721a106",
          "sha1": "4d9db7838f0dfed743e3c1ddab137c71a8741ea7",
          "md5": "7564723d9d90c88299cd9795552fb11b"
        }
      ]
    }
  ]
}
