{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mhy.social",
    "module": "wx",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "wx-1.3.1.aar",
          "url": "wx-1.3.1.aar",
          "size": 39491,
          "sha512": "63758d8d157ca054840416f5608fd423dd60fbbccfccc37fb5a9fb7208a7c5a93cef47a65dbe7b23d97f030b188dc7fa59fe0d6573fcf8fdc2e12da38c197251",
          "sha256": "9b5440df88fd5a78a248cee1887ffc7ce354412d51ae2002b0c76f708f3d347f",
          "sha1": "653229e93544f80945680fec15a180c0ea55491f",
          "md5": "7d90cd70273da0705f58ad46ac311f47"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "wx-1.3.1.aar",
          "url": "wx-1.3.1.aar",
          "size": 39491,
          "sha512": "63758d8d157ca054840416f5608fd423dd60fbbccfccc37fb5a9fb7208a7c5a93cef47a65dbe7b23d97f030b188dc7fa59fe0d6573fcf8fdc2e12da38c197251",
          "sha256": "9b5440df88fd5a78a248cee1887ffc7ce354412d51ae2002b0c76f708f3d347f",
          "sha1": "653229e93544f80945680fec15a180c0ea55491f",
          "md5": "7d90cd70273da0705f58ad46ac311f47"
        }
      ]
    }
  ]
}
