{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mhy.social",
    "module": "wx",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "wx-1.3.4.aar",
          "url": "wx-1.3.4.aar",
          "size": 42299,
          "sha512": "71b680854b20150723fca71613250cfcdaf971439445a3c5ed55acdfecf7c15f273dfe9552b257a611d3b1e03746af6dce2488389369e30ae66970b1f1b9f483",
          "sha256": "3a11069a5c92a09ed0ee7526e4aff1d26eef4ae9fbefc897182be90bff58a789",
          "sha1": "012cb4bb0651fe79509e54f5118b3c2f0ddfd1ea",
          "md5": "0e3c054b004981b9335962e05ca22e5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "wx-1.3.4.aar",
          "url": "wx-1.3.4.aar",
          "size": 42299,
          "sha512": "71b680854b20150723fca71613250cfcdaf971439445a3c5ed55acdfecf7c15f273dfe9552b257a611d3b1e03746af6dce2488389369e30ae66970b1f1b9f483",
          "sha256": "3a11069a5c92a09ed0ee7526e4aff1d26eef4ae9fbefc897182be90bff58a789",
          "sha1": "012cb4bb0651fe79509e54f5118b3c2f0ddfd1ea",
          "md5": "0e3c054b004981b9335962e05ca22e5b"
        }
      ]
    }
  ]
}
