{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gitee.mahongyin.social",
    "module": "wb",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.sinaweibosdk",
          "module": "core",
          "version": {
            "requires": "13.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "core",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "wb-1.3.1.aar",
          "url": "wb-1.3.1.aar",
          "size": 27208,
          "sha512": "305da21ddd3339272c6695726c1ffb7438f0d439b0bef2fd2ee356b5fa9d7ac1c36cebb5dce59e33eb1d5ca302740decaaea9c81a17da7f9457182cc6e9dcad3",
          "sha256": "07cd103ee379bd34136b8e2214bb120c89f72e1a83714d7871a490cac0c69aa7",
          "sha1": "af5ceb1fc4a880833ae4db69b10e89d50e555d8d",
          "md5": "991bde20cb65f76ba3f6739f1c3d7bac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.sinaweibosdk",
          "module": "core",
          "version": {
            "requires": "13.10.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "core",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "wb-1.3.1.aar",
          "url": "wb-1.3.1.aar",
          "size": 27208,
          "sha512": "305da21ddd3339272c6695726c1ffb7438f0d439b0bef2fd2ee356b5fa9d7ac1c36cebb5dce59e33eb1d5ca302740decaaea9c81a17da7f9457182cc6e9dcad3",
          "sha256": "07cd103ee379bd34136b8e2214bb120c89f72e1a83714d7871a490cac0c69aa7",
          "sha1": "af5ceb1fc4a880833ae4db69b10e89d50e555d8d",
          "md5": "991bde20cb65f76ba3f6739f1c3d7bac"
        }
      ]
    }
  ]
}
