{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mhy.social",
    "module": "qq",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qq-1.3.3.aar",
          "url": "qq-1.3.3.aar",
          "size": 339995,
          "sha512": "a6a429b6a4c41a04c9991081b7a1ce67eff11cfe6e3db5a962bb5cf68ff1da0f01e79278d1059a1b663f19ce82e62b27cf60edd611a2e6138dc3bd6cc2e8f1d4",
          "sha256": "8cd350816ab9d56e897ad220d2d2b5602ff5bcf23982c2aaa8d02b8eee06c862",
          "sha1": "07fb32c817cd0b6035f73700f535fc965895342a",
          "md5": "9bc2bfc0a4e6f62c693385c94c0067f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "qq-1.3.3.aar",
          "url": "qq-1.3.3.aar",
          "size": 339995,
          "sha512": "a6a429b6a4c41a04c9991081b7a1ce67eff11cfe6e3db5a962bb5cf68ff1da0f01e79278d1059a1b663f19ce82e62b27cf60edd611a2e6138dc3bd6cc2e8f1d4",
          "sha256": "8cd350816ab9d56e897ad220d2d2b5602ff5bcf23982c2aaa8d02b8eee06c862",
          "sha1": "07fb32c817cd0b6035f73700f535fc965895342a",
          "md5": "9bc2bfc0a4e6f62c693385c94c0067f2"
        }
      ]
    }
  ]
}
